import type { IClientsEntity } from "@/product-types";

export function mapClientToFormData(
  client: Partial<IClientsEntity>
): Partial<IClientsEntity> {
  return {
    first_name: client.first_name ?? "",
    last_name: client.last_name ?? "",
    national_id: client.national_id ?? "",
    idIssueDate: client.idIssueDate ?? "",
    dateOfBirth: client.dateOfBirth ?? "",
    gender: client.gender,
    relationship: client.relationship,
    phone_number: client.phone_number ?? "",
    email: client.email ?? "",
    cityOfResidence: client.cityOfResidence ?? "",
    address: client.address ?? "",
    apartmentNumber: client.apartmentNumber ?? "",
    zipCode: client.zipCode ?? "",
    employment: client.employment,
    occupation: client.occupation ?? "",
    employer: client.employer ?? "",
    companyId: client.companyId ?? "",
    american: client.american ?? false,
    americanForTax: client.americanForTax ?? false,
    tinNumber: client.tinNumber ?? "",
    englishFirstName: client.englishFirstName ?? "",
    englishLastName: client.englishLastName ?? "",
    englishCity: client.englishCity ?? "",
    englishCountry: client.englishCountry ?? "",
    clientStatus: client.clientStatus,
    notes: client.notes ?? "",
    birthCountry: client.birthCountry ?? "",
    birthCity: client.birthCity ?? "",
    parent1FirstName: client.parent1FirstName ?? "",
    parent1LastName: client.parent1LastName ?? "",
    parent1DateOfBirth: client.parent1DateOfBirth ?? "",
    parent2FirstName: client.parent2FirstName ?? "",
    parent2LastName: client.parent2LastName ?? "",
    parent2DateOfBirth: client.parent2DateOfBirth ?? "",
    bornInUSA: client.bornInUSA ?? false,
    taxCountry: client.taxCountry ?? "",
    englishStreet: client.englishStreet ?? "",
    bankName: client.bankName ?? "",
    bankCode: client.bankCode ?? "",
    branchNumber: client.branchNumber ?? "",
    accountNumber: client.accountNumber ?? "",
    beneficiariesDivide: client.beneficiariesDivide,
    beneficiariesDivideFree: client.beneficiariesDivideFree ?? "",
  };
}

export function createEmptyClientFormData(): Partial<IClientsEntity> {
  return {
    first_name: "",
    last_name: "",
    national_id: "",
    idIssueDate: "",
    dateOfBirth: "",
    gender: undefined,
    relationship: undefined,
    phone_number: "",
    email: "",
    cityOfResidence: "",
    address: "",
    apartmentNumber: "",
    zipCode: "",
    employment: undefined,
    occupation: "",
    employer: "",
    companyId: "",
    american: false,
    americanForTax: false,
    tinNumber: "",
    englishFirstName: "",
    englishLastName: "",
    englishCity: "",
    englishCountry: "",
    clientStatus: undefined,
    notes: "",
    birthCountry: "",
    birthCity: "",
    parent1FirstName: "",
    parent1LastName: "",
    parent1DateOfBirth: "",
    parent2FirstName: "",
    parent2LastName: "",
    parent2DateOfBirth: "",
    bornInUSA: false,
    taxCountry: "",
    englishStreet: "",
    bankName: "",
    bankCode: "",
    branchNumber: "",
    accountNumber: "",
    beneficiariesDivide: undefined,
    beneficiariesDivideFree: "",
  };
}