import './index.css';
import Layout from './layout';
import { Toaster} from '@/components/ui/sonner';
const LayoutComponent = ({ children }: { children: React.ReactNode }) => (<><Layout children={children} /><Toaster /></>);
const AppLayout = { id: '69db99a87d23f0bc9a294e99', name: 'AppLayout', component: LayoutComponent };
export { AppLayout };
import AgentDashboard2Component from './pages/AgentDashboard2';
const AgentDashboard2 = { id: '69db99b27d23f0bc9a295478', name: 'AgentDashboard2', component: AgentDashboard2Component };
export { AgentDashboard2 };
import AgentProfileComponent from './pages/AgentProfile';
const AgentProfile = { id: '69db99b37d23f0bc9a295509', name: 'AgentProfile', component: AgentProfileComponent };
export { AgentProfile };
import AgentsManagerComponent from './pages/AgentsManager';
const AgentsManager = { id: '69db99a87d23f0bc9a294eb1', name: 'AgentsManager', component: AgentsManagerComponent };
export { AgentsManager };
import ClientProfileComponent from './pages/ClientProfile';
const ClientProfile = { id: '69db99a87d23f0bc9a294e9f', name: 'ClientProfile', component: ClientProfileComponent };
export { ClientProfile };
import ClientsManagerComponent from './pages/ClientsManager';
const ClientsManager = { id: '69db99a87d23f0bc9a294e9c', name: 'ClientsManager', component: ClientsManagerComponent };
export { ClientsManager };
import FormDetailsComponent from './pages/FormDetails';
const FormDetails = { id: '69db99aa7d23f0bc9a294f85', name: 'FormDetails', component: FormDetailsComponent };
export { FormDetails };
import FormPreviewComponent from './pages/FormPreview';
const FormPreview = { id: '69db99aa7d23f0bc9a294f94', name: 'FormPreview', component: FormPreviewComponent };
export { FormPreview };
import FormsManagerComponent from './pages/FormsManager';
const FormsManager = { id: '69db99a87d23f0bc9a294ed2', name: 'FormsManager', component: FormsManagerComponent };
export { FormsManager };
import LoginComponent from './pages/Login';
const Login = { id: '69db99aa7d23f0bc9a294fb0', name: 'Login', component: LoginComponent };
export { Login };
import MeetingDetailsComponent from './pages/MeetingDetails';
const MeetingDetails = { id: '69db99b07d23f0bc9a29532d', name: 'MeetingDetails', component: MeetingDetailsComponent };
export { MeetingDetails };
import NewMeetingWizardComponent from './pages/NewMeetingWizard';
const NewMeetingWizard = { id: '69db99ac7d23f0bc9a2950a3', name: 'NewMeetingWizard', component: NewMeetingWizardComponent };
export { NewMeetingWizard };
import NewRequestWizardComponent from './pages/NewRequestWizard';
const NewRequestWizard = { id: '69db99ab7d23f0bc9a295022', name: 'NewRequestWizard', component: NewRequestWizardComponent };
export { NewRequestWizard };
import OfficeManagerComponent from './pages/OfficeManager';
const OfficeManager = { id: '69db99b37d23f0bc9a295564', name: 'OfficeManager', component: OfficeManagerComponent };
export { OfficeManager };
import PdfFieldEditorComponent from './pages/PdfFieldEditor';
const PdfFieldEditor = { id: '69f643d9c27354e1adf4efaf', name: 'PdfFieldEditor', component: PdfFieldEditorComponent };
export { PdfFieldEditor };
import ProviderEmailsManagerComponent from './pages/ProviderEmailsManager';
const ProviderEmailsManager = { id: '69db99b27d23f0bc9a2954c6', name: 'ProviderEmailsManager', component: ProviderEmailsManagerComponent };
export { ProviderEmailsManager };
import ProvidersManagerComponent from './pages/ProvidersManager';
const ProvidersManager = { id: '69db99a87d23f0bc9a294eae', name: 'ProvidersManager', component: ProvidersManagerComponent };
export { ProvidersManager };
import RequestsManagerComponent from './pages/RequestsManager';
const RequestsManager = { id: '69db99aa7d23f0bc9a294f91', name: 'RequestsManager', component: RequestsManagerComponent };
export { RequestsManager };
import RequestTypesManagerComponent from './pages/RequestTypesManager';
const RequestTypesManager = { id: '69db99a87d23f0bc9a294eb4', name: 'RequestTypesManager', component: RequestTypesManagerComponent };
export { RequestTypesManager };

// Standalone bootstrap for pnpm dev / pnpm preview (talk to Blocks backend via VITE_BLOCKS_API_HOST + VITE_APP_ID)
export const __standalone = { layout: AppLayout, pages: [{ id: '69db99b27d23f0bc9a295478', name: 'AgentDashboard2', component: AgentDashboard2 }, { id: '69db99b37d23f0bc9a295509', name: 'AgentProfile', component: AgentProfile }, { id: '69db99a87d23f0bc9a294eb1', name: 'AgentsManager', component: AgentsManager }, { id: '69db99a87d23f0bc9a294e9f', name: 'ClientProfile', component: ClientProfile }, { id: '69db99a87d23f0bc9a294e9c', name: 'ClientsManager', component: ClientsManager }, { id: '69db99aa7d23f0bc9a294f85', name: 'FormDetails', component: FormDetails }, { id: '69db99aa7d23f0bc9a294f94', name: 'FormPreview', component: FormPreview }, { id: '69db99a87d23f0bc9a294ed2', name: 'FormsManager', component: FormsManager }, { id: '69db99aa7d23f0bc9a294fb0', name: 'Login', component: Login }, { id: '69db99b07d23f0bc9a29532d', name: 'MeetingDetails', component: MeetingDetails }, { id: '69db99ac7d23f0bc9a2950a3', name: 'NewMeetingWizard', component: NewMeetingWizard }, { id: '69db99ab7d23f0bc9a295022', name: 'NewRequestWizard', component: NewRequestWizard }, { id: '69db99b37d23f0bc9a295564', name: 'OfficeManager', component: OfficeManager }, { id: '69f643d9c27354e1adf4efaf', name: 'PdfFieldEditor', component: PdfFieldEditor }, { id: '69db99b27d23f0bc9a2954c6', name: 'ProviderEmailsManager', component: ProviderEmailsManager }, { id: '69db99a87d23f0bc9a294eae', name: 'ProvidersManager', component: ProvidersManager }, { id: '69db99aa7d23f0bc9a294f91', name: 'RequestsManager', component: RequestsManager }, { id: '69db99a87d23f0bc9a294eb4', name: 'RequestTypesManager', component: RequestTypesManager }], defaultPageId: '69db99b27d23f0bc9a295478' };
export default __standalone;
